services:
  backend:
    build: .
    ports:
      - "8011:8010"
    volumes:
      - .:/app
    environment:
      - PORT=8010
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/ma_base_student
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
