version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
  backend:
    build: .
    ports:
      - "8010:8010"
    container_name: backend
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/student_db
