name: Build, Test and Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y  

      - name: Build and start services with docker-compose
        run: |
          docker-compose up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..15}; do
            if curl -s http://localhost:8010/health || curl -s http://localhost:8010/; then
              echo "Backend is up!"
              exit 0
            fi
            sleep 2
          done
          echo "Backend did not start in time"
          docker-compose logs backend
          exit 1

      - name: Stop services
        run: docker-compose down

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
       - name: Trigger Render Deploy
         env:
            RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
            RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
         run: |
            curl -X POST https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys \
                 -H 'Accept: application/json' \
                 -H "Authorization: Bearer $RENDER_API_KEY" \
                 -d ''
