name: Test and Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'  

      - name: Install dependencies
        run: npm install

      - name: Check that app starts without error
        run: |
            npm start &                   # lance l'app en arrière-plan
            SERVER_PID=$!                # enregistre le PID du serveur
            sleep 5                      # attend quelques secondes
            kill $SERVER_PID             # arrête le serveur proprement


  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/v1/services/srv-d0d4l9umcj7s739rmni0/deploys \
          -H 'Accept: application/json' \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d ''
